// lib/core/services/profile_manager.dart

import 'package:shared_preferences/shared_preferences.dart';
import 'package:uuid/uuid.dart';

import '../data/supabase_db.dart';

/// Manages the local user's profile — synced to Supabase.
///
/// On first launch, the user picks a role (student/teacher) and enters
/// their name. This is stored in Supabase `profiles` table keyed by
/// a unique device ID (UUID persisted in SharedPreferences).
///
/// Provides [profileId] for all Supabase operations that need the user's UUID.
class ProfileManager {
  ProfileManager._();
  static final instance = ProfileManager._();

  static const _deviceIdKey = 'greymatter_device_id';

  String? _profileId;
  String? _name;
  String? _role;
  String? _gradeLevel;
  List<String> _subjects = [];
  String? _deviceId;
  String? _lastSessionCode;

  /// Supabase profile UUID. Null until [loadProfile] is called.
  String? get profileId => _profileId;

  /// User's display name.
  String? get name => _name;

  /// 'student' or 'teacher'.
  String? get role => _role;

  /// Grade level (students only).
  String? get gradeLevel => _gradeLevel;

  /// Subjects of interest (students only).
  List<String> get subjects => _subjects;

  /// Last session code generated by this student.
  String? get lastSessionCode => _lastSessionCode;

  /// Store the current session code so it can be viewed from Settings.
  void setSessionCode(String code) => _lastSessionCode = code;

  /// Whether a profile has been loaded/created.
  bool get hasProfile => _profileId != null;

  /// Whether the user is a student.
  bool get isStudent => _role == 'student';

  /// Whether the user is a teacher.
  bool get isTeacher => _role == 'teacher';

  /// Get or generate a stable device ID, persisted across app restarts.
  Future<String> getDeviceId() async {
    if (_deviceId != null) return _deviceId!;

    final prefs = await SharedPreferences.getInstance();
    var id = prefs.getString(_deviceIdKey);
    if (id == null) {
      id = const Uuid().v4();
      await prefs.setString(_deviceIdKey, id);
    }
    _deviceId = id;
    return id;
  }

  /// Load existing profile from Supabase, or return false if none exists.
  Future<bool> loadProfile() async {
    try {
      final deviceId = await getDeviceId();
      final data = await SupabaseDb.instance.profileByDeviceId(deviceId);
      if (data != null) {
        _profileId = data['id'] as String;
        _name = data['name'] as String;
        _role = data['role'] as String;
        _gradeLevel = data['grade_level'] as String?;
        _subjects = List<String>.from(data['subjects'] ?? []);
        return true;
      }
    } catch (_) {}
    return false;
  }

  /// Create or update profile in Supabase.
  Future<void> saveProfile({
    required String name,
    required String role,
    String? gradeLevel,
    List<String> subjects = const [],
  }) async {
    final deviceId = await getDeviceId();
    final data = await SupabaseDb.instance.upsertProfile(
      deviceId: deviceId,
      name: name,
      role: role,
      gradeLevel: gradeLevel,
      subjects: subjects,
    );

    _profileId = data['id'] as String;
    _name = name;
    _role = role;
    _gradeLevel = gradeLevel;
    _subjects = subjects;
  }

  /// Update just the name.
  Future<void> updateName(String name) async {
    if (_role == null) return;
    await saveProfile(
      name: name,
      role: _role!,
      gradeLevel: _gradeLevel,
      subjects: _subjects,
    );
  }

  /// Clear local state (e.g., on logout/reset).
  void clear() {
    _profileId = null;
    _name = null;
    _role = null;
    _gradeLevel = null;
    _subjects = [];
  }
}
